# Generated by Django 5.1.15 on 2026-08-28 16:30

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("legajos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoLicencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "codigo",
                    models.CharField(
                        blank=True,
                        help_text='Ej.: "Art. 76".',
                        max_length=20,
                        verbose_name="código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=150, verbose_name="denominación"),
                ),
                (
                    "con_goce",
                    models.BooleanField(
                        default=True,
                        help_text="Si no tiene goce, el descuento se informa a quien liquida.",
                        verbose_name="con goce de haberes",
                    ),
                ),
                (
                    "impacta_haberes",
                    models.BooleanField(
                        default=True,
                        help_text="Solo se informan las novedades que generan descuento o pago adicional.",
                        verbose_name="impacta en la liquidación",
                    ),
                ),
                (
                    "requiere_certificado",
                    models.BooleanField(
                        default=False, verbose_name="requiere certificado"
                    ),
                ),
                (
                    "tope_dias_anual",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="tope de días por año",
                    ),
                ),
                (
                    "tope_dias_por_caso",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="tope de días por caso",
                    ),
                ),
                (
                    "tope_dias_consecutivos",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="máximo de días consecutivos",
                    ),
                ),
                (
                    "extensible_con_aval",
                    models.BooleanField(
                        default=False,
                        help_text="Ej.: enfermedad más allá del tope, con junta médica.",
                        verbose_name="se puede extender con aval",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de licencia",
                "verbose_name_plural": "tipos de licencia",
                "ordering": ["codigo", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Licencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="desde")),
                ("fecha_fin", models.DateField(verbose_name="hasta")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOLICITADA", "Solicitada"),
                            ("APROBADA", "Aprobada"),
                            ("RECHAZADA", "Rechazada"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="SOLICITADA",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "certificado",
                    models.FileField(
                        blank=True, upload_to="licencias/", verbose_name="certificado"
                    ),
                ),
                (
                    "aval",
                    models.FileField(
                        blank=True,
                        help_text="Junta médica u otra autorización, cuando se supera el tope.",
                        upload_to="licencias/avales/",
                        verbose_name="aval de la extensión",
                    ),
                ),
                (
                    "solicitada_en",
                    models.DateField(
                        default=datetime.date.today, verbose_name="solicitada el"
                    ),
                ),
                (
                    "resuelta_en",
                    models.DateField(blank=True, null=True, verbose_name="resuelta el"),
                ),
                (
                    "motivo_rechazo",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="motivo del rechazo"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "cargos",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Si se deja vacío, se entiende que afecta a todos los cargos vigentes.",
                        related_name="licencias",
                        to="legajos.cargo",
                        verbose_name="cargos afectados",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licencias",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
                (
                    "prorroga_de",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prorrogas",
                        to="licencias.licencia",
                        verbose_name="prórroga de",
                    ),
                ),
                (
                    "resuelta_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licencias_resueltas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="resuelta por",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licencias",
                        to="licencias.tipolicencia",
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "licencia",
                "verbose_name_plural": "licencias",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Cobertura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SUPLENTE", "Se designa un suplente"),
                            (
                                "SIN_COBERTURA",
                                "Sin cobertura (los alumnos quedan libres)",
                            ),
                        ],
                        default="SUPLENTE",
                        max_length=15,
                        verbose_name="decisión",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="desde")),
                ("fecha_fin", models.DateField(verbose_name="hasta")),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observaciones"
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coberturas",
                        to="legajos.cargo",
                        verbose_name="cargo del titular",
                    ),
                ),
                (
                    "cargo_suplente",
                    models.OneToOneField(
                        blank=True,
                        help_text="Se crea automáticamente al designar, para que el suplente tenga su cargo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cobertura_de_origen",
                        to="legajos.cargo",
                        verbose_name="designación del suplente",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "suplente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="suplencias",
                        to="legajos.legajo",
                        verbose_name="suplente",
                    ),
                ),
                (
                    "licencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coberturas",
                        to="licencias.licencia",
                        verbose_name="licencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "cobertura",
                "verbose_name_plural": "coberturas de licencias",
                "ordering": ["-fecha_inicio"],
                "indexes": [
                    models.Index(
                        fields=["institucion", "fecha_inicio", "fecha_fin"],
                        name="licencias_c_institu_c96cd3_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tipolicencia",
            constraint=models.UniqueConstraint(
                fields=("institucion", "nombre"), name="tipo_licencia_unico_por_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="licencia",
            index=models.Index(
                fields=["institucion", "fecha_inicio", "fecha_fin"],
                name="licencias_l_institu_550947_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="licencia",
            index=models.Index(
                fields=["legajo", "estado"], name="licencias_l_legajo__8335f9_idx"
            ),
        ),
    ]
