# Generated by Django 5.1.15 on 2026-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cobertura",
            name="notificada_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="avisado el"
            ),
        ),
        migrations.AddField(
            model_name="cobertura",
            name="notificada_por",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EMAIL", "Email"),
                    ("WHATSAPP", "WhatsApp"),
                    ("OTRO", "En persona o por teléfono"),
                ],
                max_length=10,
                verbose_name="avisado por",
            ),
        ),
    ]
