# Generated by Django 5.1.15 on 2026-08-30 14:43

import core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licencias", "0003_alter_licencia_aval_alter_licencia_certificado"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licencia",
            name="aval",
            field=models.FileField(
                blank=True,
                help_text="Junta médica u otra autorización, cuando se supera el tope.",
                upload_to=core.archivos.CarpetaProtegida("licencias/avales"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="aval de la extensión",
            ),
        ),
        migrations.AlterField(
            model_name="licencia",
            name="certificado",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("licencias"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="certificado",
            ),
        ),
    ]
