# Generated by Django 5.1.15 on 2026-08-28 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_institucion_latitud_institucion_longitud_and_more"),
        ("legajos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoInasistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("fecha", models.DateField(verbose_name="fecha de la ausencia")),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("ENFERMEDAD", "Enfermedad"),
                            ("FAMILIAR", "Atención de familiar"),
                            ("PARTICULAR", "Razones particulares"),
                            ("TRAMITE", "Trámite o turno médico"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=12,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "detalle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="detalle"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ENVIADO", "Enviado"),
                            ("VISTO", "Visto por secretaría"),
                            ("ANULADO", "Anulado por el docente"),
                        ],
                        default="ENVIADO",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "visto_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="visto en"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avisos",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "aviso de inasistencia",
                "verbose_name_plural": "avisos de inasistencia",
                "ordering": ["-fecha", "-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["institucion", "fecha"],
                        name="portal_avis_institu_586908_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legajo", "fecha"), name="un_aviso_por_dia"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Fichada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                ("hora", models.TimeField(verbose_name="hora")),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SALIDA", "Salida")],
                        default="ENTRADA",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "latitud",
                    models.FloatField(blank=True, null=True, verbose_name="latitud"),
                ),
                (
                    "longitud",
                    models.FloatField(blank=True, null=True, verbose_name="longitud"),
                ),
                (
                    "precision_metros",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="precisión (m)"
                    ),
                ),
                (
                    "distancia_metros",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="distancia a la escuela (m)"
                    ),
                ),
                (
                    "en_la_escuela",
                    models.BooleanField(
                        default=False,
                        help_text="Se calcula al fichar, comparando con la ubicación de la escuela.",
                        verbose_name="dentro del radio",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="observaciones"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fichadas",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "fichada",
                "verbose_name_plural": "fichadas",
                "ordering": ["-fecha", "-hora"],
                "indexes": [
                    models.Index(
                        fields=["institucion", "fecha"],
                        name="portal_fich_institu_a22ef1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("legajo", "fecha", "tipo"),
                        name="una_fichada_por_tipo_y_dia",
                    )
                ],
            },
        ),
    ]
