# Generated by Django 5.1.15 on 2026-08-28 15:39

import core.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Institucion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "nombre_corto",
                    models.CharField(
                        help_text="Para encabezados y listados.",
                        max_length=50,
                        verbose_name="nombre corto",
                    ),
                ),
                (
                    "cue",
                    models.CharField(
                        blank=True,
                        help_text="Código Único de Establecimiento.",
                        max_length=20,
                        verbose_name="CUE",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El CUIT/CUIL debe tener 11 dígitos (con o sin guiones).",
                                regex="^\\d{2}-?\\d{8}-?\\d$",
                            )
                        ],
                        verbose_name="CUIT",
                    ),
                ),
                (
                    "jurisdiccion",
                    models.CharField(
                        choices=[
                            ("AR-B", "Buenos Aires"),
                            ("AR-C", "Ciudad Autónoma de Buenos Aires"),
                            ("AR-K", "Catamarca"),
                            ("AR-H", "Chaco"),
                            ("AR-U", "Chubut"),
                            ("AR-X", "Córdoba"),
                            ("AR-W", "Corrientes"),
                            ("AR-E", "Entre Ríos"),
                            ("AR-P", "Formosa"),
                            ("AR-Y", "Jujuy"),
                            ("AR-L", "La Pampa"),
                            ("AR-F", "La Rioja"),
                            ("AR-M", "Mendoza"),
                            ("AR-N", "Misiones"),
                            ("AR-Q", "Neuquén"),
                            ("AR-R", "Río Negro"),
                            ("AR-A", "Salta"),
                            ("AR-J", "San Juan"),
                            ("AR-D", "San Luis"),
                            ("AR-Z", "Santa Cruz"),
                            ("AR-S", "Santa Fe"),
                            ("AR-G", "Santiago del Estero"),
                            ("AR-V", "Tierra del Fuego"),
                            ("AR-T", "Tucumán"),
                        ],
                        default="AR-D",
                        max_length=8,
                        verbose_name="jurisdicción",
                    ),
                ),
                (
                    "domicilio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="domicilio"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="localidad"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "creada_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada en"),
                ),
            ],
            options={
                "verbose_name": "institución",
                "verbose_name_plural": "instituciones",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email"
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="apellido")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="teléfono"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Permite entrar al panel de administración.",
                        verbose_name="acceso al admin",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="alta"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "usuario",
                "verbose_name_plural": "usuarios",
                "ordering": ["apellido", "nombre"],
            },
            managers=[
                ("objects", core.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name="Membresia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("SECRETARIA", "Secretaría"),
                            ("DIRECTIVO", "Equipo directivo"),
                            ("DOCENTE", "Docente"),
                            ("LIQUIDADOR", "Liquidador / Contador"),
                        ],
                        max_length=20,
                        verbose_name="rol",
                    ),
                ),
                ("activa", models.BooleanField(default=True, verbose_name="activa")),
                (
                    "creada_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creada en"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membresias",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "membresía",
                "verbose_name_plural": "membresías",
                "ordering": ["institucion", "usuario"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "institucion", "rol"),
                        name="membresia_unica_por_rol",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("CREACION", "Creación"),
                            ("MODIFICACION", "Modificación"),
                            ("BAJA", "Baja"),
                            ("CIERRE_PERIODO", "Cierre de período"),
                            ("REAPERTURA_PERIODO", "Reapertura de período"),
                            ("APROBACION", "Aprobación"),
                            ("EXPORTACION", "Exportación de datos"),
                        ],
                        max_length=30,
                        verbose_name="acción",
                    ),
                ),
                ("modelo", models.CharField(max_length=100, verbose_name="modelo")),
                (
                    "objeto_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="id del objeto"
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="descripción"
                    ),
                ),
                (
                    "datos",
                    models.JSONField(blank=True, default=dict, verbose_name="datos"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="fecha y hora"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditoria",
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditoria",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de auditoría",
                "verbose_name_plural": "registros de auditoría",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["institucion", "-creado_en"],
                        name="core_regist_institu_004bc3_idx",
                    ),
                    models.Index(
                        fields=["modelo", "objeto_id"],
                        name="core_regist_modelo_a44527_idx",
                    ),
                ],
            },
        ),
    ]
