# Generated by Django 5.1.15 on 2026-08-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="latitud",
            field=models.FloatField(
                blank=True,
                help_text="Se puede copiar de Google Maps.",
                null=True,
                verbose_name="latitud",
            ),
        ),
        migrations.AddField(
            model_name="institucion",
            name="longitud",
            field=models.FloatField(blank=True, null=True, verbose_name="longitud"),
        ),
        migrations.AddField(
            model_name="institucion",
            name="radio_fichaje_metros",
            field=models.PositiveIntegerField(
                default=200,
                help_text="Distancia máxima desde la escuela para considerar válida una fichada.",
                verbose_name="radio para fichar (m)",
            ),
        ),
    ]
