# Generated by Django 5.1.15 on 2026-08-29 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_institucion_latitud_institucion_longitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institucion",
            name="color",
            field=models.CharField(
                blank=True,
                help_text='Hexadecimal, ej.: "#c2560f". Vacío deja el color del sistema.',
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message='El color va en hexadecimal de seis dígitos, por ejemplo "#c2560f".',
                        regex="^#[0-9a-fA-F]{6}$",
                    )
                ],
                verbose_name="color de la escuela",
            ),
        ),
        migrations.AddField(
            model_name="institucion",
            name="emblema",
            field=models.CharField(
                blank=True,
                help_text="Un emoji que identifique a la escuela. Va en el encabezado y en la solapa.",
                max_length=4,
                verbose_name="emblema",
            ),
        ),
    ]
