# Generated by Django 5.1.15 on 2026-08-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_identidad_visual"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="vio_la_bienvenida",
            field=models.BooleanField(default=False, verbose_name="vio la bienvenida"),
        ),
    ]
