# Generated by Django 5.1.15 on 2026-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_bienvenida"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("ACCESO", "Ingreso al sistema"),
                    ("ACCESO_FALLIDO", "Intento de ingreso fallido"),
                    ("BLOQUEO", "Ingreso bloqueado"),
                    ("CREACION", "Creación"),
                    ("MODIFICACION", "Modificación"),
                    ("BAJA", "Baja"),
                    ("CIERRE_PERIODO", "Cierre de período"),
                    ("REAPERTURA_PERIODO", "Reapertura de período"),
                    ("APROBACION", "Aprobación"),
                    ("EXPORTACION", "Exportación de datos"),
                ],
                max_length=30,
                verbose_name="acción",
            ),
        ),
        migrations.CreateModel(
            name="IntentoDeAcceso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.CharField(max_length=254, verbose_name="email probado"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="dirección IP"
                    ),
                ),
                ("exito", models.BooleanField(default=False, verbose_name="entró")),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cuándo"),
                ),
            ],
            options={
                "verbose_name": "intento de acceso",
                "verbose_name_plural": "intentos de acceso",
                "ordering": ["-creado_en"],
                "indexes": [
                    models.Index(
                        fields=["email", "creado_en"],
                        name="core_intent_email_90cc14_idx",
                    ),
                    models.Index(
                        fields=["ip", "creado_en"], name="core_intent_ip_ade5eb_idx"
                    ),
                ],
            },
        ),
    ]
