# Generated by Django 5.1.15 on 2026-08-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_intentos_de_acceso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registroauditoria",
            name="accion",
            field=models.CharField(
                choices=[
                    ("ACCESO", "Ingreso al sistema"),
                    ("ACCESO_FALLIDO", "Intento de ingreso fallido"),
                    ("BLOQUEO", "Ingreso bloqueado"),
                    ("CREACION", "Creación"),
                    ("MODIFICACION", "Modificación"),
                    ("BAJA", "Baja"),
                    ("CIERRE_PERIODO", "Cierre de período"),
                    ("REAPERTURA_PERIODO", "Reapertura de período"),
                    ("APROBACION", "Aprobación"),
                    ("EXPORTACION", "Exportación de datos"),
                    ("IMPORTACION", "Carga masiva desde planilla"),
                ],
                max_length=30,
                verbose_name="acción",
            ),
        ),
    ]
