# Generated by Django 5.1.15 on 2026-08-28 15:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CicloLectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "anio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="año",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="inicio de clases")),
                ("fecha_fin", models.DateField(verbose_name="fin de clases")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PLANIFICACION", "En planificación"),
                            ("ACTIVO", "Activo"),
                            ("CERRADO", "Cerrado"),
                        ],
                        default="PLANIFICACION",
                        max_length=15,
                        verbose_name="estado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "ciclo lectivo",
                "verbose_name_plural": "ciclos lectivos",
                "ordering": ["-anio"],
            },
        ),
        migrations.CreateModel(
            name="EsquemaHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej.: "Con almuerzo".',
                        max_length=80,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "predeterminado",
                    models.BooleanField(
                        default=False,
                        help_text="Se propone al crear un curso de este turno.",
                        verbose_name="predeterminado",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "esquema horario",
                "verbose_name_plural": "esquemas horarios",
                "ordering": ["turno", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="BloqueHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                        ],
                        verbose_name="día",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="orden en el día"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CLASE", "Hora de clase"),
                            ("RECREO", "Recreo"),
                            ("ALMUERZO", "Almuerzo"),
                            ("OTRO", "Otro"),
                        ],
                        default="CLASE",
                        max_length=10,
                        verbose_name="tipo",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="desde")),
                ("hora_fin", models.TimeField(verbose_name="hasta")),
                (
                    "etiqueta",
                    models.CharField(
                        blank=True,
                        help_text='Opcional. Ej.: "1ª hora".',
                        max_length=40,
                        verbose_name="etiqueta",
                    ),
                ),
                (
                    "esquema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bloques",
                        to="estructura.esquemahorario",
                        verbose_name="esquema",
                    ),
                ),
            ],
            options={
                "verbose_name": "bloque horario",
                "verbose_name_plural": "bloques horarios",
                "ordering": ["esquema", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("INICIAL", "Inicial"),
                            ("PRIMARIO", "Primario"),
                            ("SECUNDARIO", "Secundario"),
                        ],
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        blank=True,
                        help_text="Opcional: cómo lo llama la escuela.",
                        max_length=100,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "nivel",
                "verbose_name_plural": "niveles",
                "ordering": ["orden", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("nombre", models.CharField(max_length=120, verbose_name="nombre")),
                (
                    "abreviatura",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="abreviatura"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materias",
                        to="estructura.nivel",
                        verbose_name="nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "materia",
                "verbose_name_plural": "materias",
                "ordering": ["nivel", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "anio_estudio",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="año de estudio",
                    ),
                ),
                (
                    "division",
                    models.CharField(
                        help_text='Ej.: "A".', max_length=5, verbose_name="división"
                    ),
                ),
                (
                    "ciclo_lectivo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cursos",
                        to="estructura.ciclolectivo",
                        verbose_name="ciclo lectivo",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "esquema_horario",
                    models.ForeignKey(
                        help_text="Grilla que sigue este curso (con almuerzo, sin almuerzo, etc.).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="estructura.esquemahorario",
                        verbose_name="esquema horario",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cursos",
                        to="estructura.nivel",
                        verbose_name="nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "curso",
                "verbose_name_plural": "cursos",
                "ordering": ["ciclo_lectivo", "nivel", "anio_estudio", "division"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej.: "1er cuatrimestre".',
                        max_length=50,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=1, verbose_name="orden"),
                ),
                ("fecha_inicio", models.DateField(verbose_name="desde")),
                ("fecha_fin", models.DateField(verbose_name="hasta")),
                (
                    "ciclo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodos",
                        to="estructura.ciclolectivo",
                        verbose_name="ciclo lectivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "período académico",
                "verbose_name_plural": "períodos académicos",
                "ordering": ["ciclo", "orden"],
            },
        ),
        migrations.CreateModel(
            name="MateriaPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "horas_semanales",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="horas semanales",
                    ),
                ),
                (
                    "vigencia",
                    models.CharField(
                        choices=[
                            ("ANUAL", "Todo el año"),
                            ("PERIODO", "Solo un período"),
                        ],
                        default="ANUAL",
                        max_length=10,
                        verbose_name="vigencia",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="estructura.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planes",
                        to="estructura.materia",
                        verbose_name="materia",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo si la materia se dicta en un período y no todo el año.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planes",
                        to="estructura.periodoacademico",
                        verbose_name="período",
                    ),
                ),
            ],
            options={
                "verbose_name": "materia del plan",
                "verbose_name_plural": "plan de estudios",
                "ordering": ["curso", "materia"],
            },
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej.: "Mañana".', max_length=50, verbose_name="nombre"
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="entrada")),
                ("hora_fin", models.TimeField(verbose_name="salida")),
                (
                    "orden",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turnos",
                        to="estructura.nivel",
                        verbose_name="nivel",
                    ),
                ),
            ],
            options={
                "verbose_name": "turno",
                "verbose_name_plural": "turnos",
                "ordering": ["nivel", "orden", "hora_inicio"],
            },
        ),
        migrations.AddField(
            model_name="esquemahorario",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="esquemas",
                to="estructura.turno",
                verbose_name="turno",
            ),
        ),
        migrations.AddField(
            model_name="curso",
            name="turno",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cursos",
                to="estructura.turno",
                verbose_name="turno",
            ),
        ),
        migrations.AddConstraint(
            model_name="ciclolectivo",
            constraint=models.UniqueConstraint(
                fields=("institucion", "anio"), name="ciclo_unico_por_anio"
            ),
        ),
        migrations.AddIndex(
            model_name="bloquehorario",
            index=models.Index(
                fields=["esquema", "dia_semana"], name="estructura__esquema_b41bfe_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bloquehorario",
            constraint=models.UniqueConstraint(
                fields=("esquema", "dia_semana", "orden"),
                name="bloque_unico_por_dia_y_orden",
            ),
        ),
        migrations.AddConstraint(
            model_name="nivel",
            constraint=models.UniqueConstraint(
                fields=("institucion", "tipo"), name="nivel_unico_por_tipo"
            ),
        ),
        migrations.AddConstraint(
            model_name="materia",
            constraint=models.UniqueConstraint(
                fields=("institucion", "nivel", "nombre"),
                name="materia_unica_por_nivel",
            ),
        ),
        migrations.AddConstraint(
            model_name="periodoacademico",
            constraint=models.UniqueConstraint(
                fields=("ciclo", "orden"), name="periodo_unico_por_orden"
            ),
        ),
        migrations.AddConstraint(
            model_name="materiaplan",
            constraint=models.UniqueConstraint(
                fields=("curso", "materia", "periodo"),
                name="materia_unica_por_curso_y_periodo",
            ),
        ),
        migrations.AddConstraint(
            model_name="turno",
            constraint=models.UniqueConstraint(
                fields=("nivel", "nombre"), name="turno_unico_por_nivel"
            ),
        ),
        migrations.AddConstraint(
            model_name="esquemahorario",
            constraint=models.UniqueConstraint(
                fields=("turno", "nombre"), name="esquema_unico_por_turno"
            ),
        ),
        migrations.AddConstraint(
            model_name="curso",
            constraint=models.UniqueConstraint(
                fields=("ciclo_lectivo", "nivel", "anio_estudio", "division"),
                name="curso_unico_por_ciclo",
            ),
        ),
    ]
