# Generated by Django 5.1.15 on 2026-08-28 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("legajos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroAsistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PRESENTE", "Presente"),
                            ("AUSENTE", "Ausente"),
                            ("TARDE", "Llegada tarde"),
                            ("RETIRO", "Retiro anticipado"),
                            ("PARCIAL", "Ausencia parcial"),
                        ],
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "horas_afectadas",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Para ausencias parciales: cuántas horas no dio.",
                        null=True,
                        verbose_name="horas afectadas",
                    ),
                ),
                (
                    "hora",
                    models.TimeField(
                        blank=True,
                        help_text="Hora de llegada o de retiro, según el caso.",
                        null=True,
                        verbose_name="hora",
                    ),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observaciones"
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
            ],
            options={
                "verbose_name": "registro de asistencia",
                "verbose_name_plural": "asistencia",
                "ordering": ["-fecha", "legajo"],
            },
        ),
    ]
