# Generated by Django 5.1.15 on 2026-08-28 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asistencia", "0001_initial"),
        ("licencias", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="registroasistencia",
            name="licencia",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias",
                to="licencias.licencia",
                verbose_name="licencia que la justifica",
            ),
        ),
        migrations.AddField(
            model_name="registroasistencia",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_registradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="registrado por",
            ),
        ),
        migrations.AddIndex(
            model_name="registroasistencia",
            index=models.Index(
                fields=["institucion", "fecha"], name="asistencia__institu_5efb49_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="registroasistencia",
            constraint=models.UniqueConstraint(
                fields=("legajo", "fecha"), name="un_registro_por_persona_y_dia"
            ),
        ),
    ]
