# Generated by Django 5.1.15 on 2026-08-28 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("legajos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodoNovedades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                ("anio", models.PositiveSmallIntegerField(verbose_name="año")),
                ("mes", models.PositiveSmallIntegerField(verbose_name="mes")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ABIERTO", "Abierto"),
                            ("CERRADO", "Cerrado"),
                            ("REABIERTO", "Reabierto"),
                        ],
                        default="ABIERTO",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "compilado_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="compilado en"
                    ),
                ),
                (
                    "cerrado_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cerrado en"
                    ),
                ),
                (
                    "motivo_reapertura",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        verbose_name="motivo de la reapertura",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "cerrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodos_cerrados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="cerrado por",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "período de novedades",
                "verbose_name_plural": "períodos de novedades",
                "ordering": ["-anio", "-mes"],
            },
        ),
        migrations.CreateModel(
            name="Novedad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LICENCIA", "Licencia"),
                            ("ALTA", "Alta"),
                            ("CESE", "Cese"),
                            ("RENUNCIA", "Renuncia"),
                            ("CAMBIO", "Cambio"),
                            ("INASISTENCIA", "Inasistencia injustificada"),
                            ("TARDANZA", "Llegadas tarde"),
                            ("OTRA", "Otra novedad"),
                        ],
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "destino",
                    models.CharField(
                        choices=[
                            ("OFICIAL", "Planilla Oficial"),
                            ("INTERNA", "Planilla Interna"),
                        ],
                        max_length=10,
                        verbose_name="planilla",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="fecha")),
                (
                    "fecha_fin",
                    models.DateField(blank=True, null=True, verbose_name="hasta"),
                ),
                (
                    "dias",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="días"
                    ),
                ),
                (
                    "horas",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="horas"
                    ),
                ),
                (
                    "espacio",
                    models.CharField(
                        blank=True,
                        help_text="Materia o denominación del cargo, como figura en la planilla.",
                        max_length=200,
                        verbose_name="espacio curricular / cargo",
                    ),
                ),
                (
                    "motivo",
                    models.CharField(blank=True, max_length=200, verbose_name="motivo"),
                ),
                (
                    "reemplazante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="reemplazante"
                    ),
                ),
                (
                    "presenta_certificado",
                    models.BooleanField(
                        default=False, verbose_name="presenta certificado"
                    ),
                ),
                (
                    "jornada_completa",
                    models.BooleanField(default=False, verbose_name="jornada completa"),
                ),
                (
                    "tiempo_determinado",
                    models.BooleanField(
                        default=False, verbose_name="tiempo determinado"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "impacta_haberes",
                    models.BooleanField(
                        default=True,
                        help_text="Solo se informa lo que genera descuento o pago adicional.",
                        verbose_name="impacta en la liquidación",
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("AUTOMATICA", "Compilada por el sistema"),
                            ("MANUAL", "Cargada a mano"),
                        ],
                        default="AUTOMATICA",
                        max_length=12,
                        verbose_name="origen",
                    ),
                ),
                (
                    "clave_origen",
                    models.CharField(
                        blank=True,
                        help_text="Identifica el hecho que la generó, para no duplicarla al recompilar.",
                        max_length=100,
                        verbose_name="clave de origen",
                    ),
                ),
                (
                    "informada",
                    models.BooleanField(
                        default=False, verbose_name="informada al liquidador"
                    ),
                ),
                (
                    "informada_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="informada el"
                    ),
                ),
                (
                    "congelada",
                    models.BooleanField(
                        default=False,
                        help_text="Se congela al cerrar el período.",
                        verbose_name="congelada",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novedades",
                        to="legajos.cargo",
                        verbose_name="cargo",
                    ),
                ),
                (
                    "informada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="novedades_informadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="informada por",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novedades",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novedades",
                        to="novedades.periodonovedades",
                        verbose_name="período",
                    ),
                ),
            ],
            options={
                "verbose_name": "novedad",
                "verbose_name_plural": "novedades",
                "ordering": ["destino", "legajo__apellido", "fecha"],
            },
        ),
        migrations.AddConstraint(
            model_name="periodonovedades",
            constraint=models.UniqueConstraint(
                fields=("institucion", "anio", "mes"), name="periodo_novedades_unico"
            ),
        ),
        migrations.AddIndex(
            model_name="novedad",
            index=models.Index(
                fields=["periodo", "destino"], name="novedades_n_periodo_270ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="novedad",
            index=models.Index(
                fields=["periodo", "informada"], name="novedades_n_periodo_d2ed23_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="novedad",
            constraint=models.UniqueConstraint(
                condition=models.Q(("clave_origen__gt", "")),
                fields=("periodo", "clave_origen"),
                name="una_novedad_por_hecho",
            ),
        ),
    ]
