# Generated by Django 5.1.15 on 2026-08-31 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novedades", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="periodonovedades",
            options={
                "ordering": ["-anio", "-mes"],
                "permissions": [
                    (
                        "ver_sin_cerrar_periodonovedades",
                        "Puede ver un período de novedades antes de que se cierre",
                    )
                ],
                "verbose_name": "período de novedades",
                "verbose_name_plural": "períodos de novedades",
            },
        ),
    ]
