# Generated by Django 5.1.15 on 2026-08-28 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("estructura", "0001_initial"),
        ("legajos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeclaracionDisponibilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "presentada_en",
                    models.DateField(
                        blank=True, null=True, verbose_name="presentada el"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True,
                        upload_to="ddjj/",
                        verbose_name="declaración firmada",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaraciones",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="declaraciones",
                        to="estructura.periodoacademico",
                        verbose_name="período",
                    ),
                ),
            ],
            options={
                "verbose_name": "declaración de disponibilidad",
                "verbose_name_plural": "declaraciones de disponibilidad (DDJJ)",
                "ordering": ["periodo", "legajo"],
            },
        ),
        migrations.CreateModel(
            name="FranjaNoDisponible",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                        ],
                        verbose_name="día",
                    ),
                ),
                ("hora_desde", models.TimeField(verbose_name="desde")),
                ("hora_hasta", models.TimeField(verbose_name="hasta")),
                (
                    "motivo",
                    models.CharField(
                        choices=[
                            ("OTRA_ESCUELA", "Trabaja en otra institución"),
                            ("ESTUDIO", "Estudio o capacitación"),
                            ("PERSONAL", "Motivo personal"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRA_ESCUELA",
                        max_length=15,
                        verbose_name="motivo",
                    ),
                ),
                (
                    "institucion_externa",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="institución"
                    ),
                ),
                (
                    "es_preferencia",
                    models.BooleanField(
                        default=False,
                        help_text="Si se marca, el generador intenta evitarla pero puede usarla si no hay otra opción.",
                        verbose_name="es solo una preferencia",
                    ),
                ),
                (
                    "declaracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="franjas",
                        to="horarios.declaraciondisponibilidad",
                        verbose_name="declaración",
                    ),
                ),
            ],
            options={
                "verbose_name": "franja no disponible",
                "verbose_name_plural": "franjas no disponibles",
                "ordering": ["dia_semana", "hora_desde"],
            },
        ),
        migrations.CreateModel(
            name="VersionHorario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej.: "Borrador 1".',
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("VIGENTE", "Vigente"),
                            ("HISTORICO", "Histórico"),
                        ],
                        default="BORRADOR",
                        max_length=12,
                        verbose_name="estado",
                    ),
                ),
                (
                    "generada_en",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="generada en"
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        verbose_name="parámetros de generación",
                    ),
                ),
                (
                    "resumen",
                    models.JSONField(blank=True, default=dict, verbose_name="resumen"),
                ),
                ("notas", models.TextField(blank=True, verbose_name="notas")),
                (
                    "generada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="horarios_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="generada por",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versiones_horario",
                        to="estructura.periodoacademico",
                        verbose_name="período",
                    ),
                ),
            ],
            options={
                "verbose_name": "versión de horario",
                "verbose_name_plural": "versiones de horario",
                "ordering": ["-periodo__ciclo__anio", "periodo__orden", "-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="AsignacionHoraria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dia_semana",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Lunes"),
                            (1, "Martes"),
                            (2, "Miércoles"),
                            (3, "Jueves"),
                            (4, "Viernes"),
                            (5, "Sábado"),
                        ],
                        verbose_name="día",
                    ),
                ),
                ("hora_inicio", models.TimeField(verbose_name="desde")),
                ("hora_fin", models.TimeField(verbose_name="hasta")),
                (
                    "bloqueada",
                    models.BooleanField(
                        default=False,
                        help_text="El generador no la mueve: sirve para fijar lo que ya está bien.",
                        verbose_name="bloqueada",
                    ),
                ),
                (
                    "bloque",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="estructura.bloquehorario",
                        verbose_name="bloque",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones",
                        to="legajos.cargo",
                        verbose_name="cargo del docente",
                    ),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="estructura.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        blank=True,
                        help_text="Se completa solo a partir del cargo.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones",
                        to="legajos.legajo",
                        verbose_name="docente",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asignaciones",
                        to="estructura.materia",
                        verbose_name="materia",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asignaciones",
                        to="horarios.versionhorario",
                        verbose_name="versión",
                    ),
                ),
            ],
            options={
                "verbose_name": "asignación horaria",
                "verbose_name_plural": "asignaciones horarias",
                "ordering": ["version", "curso", "dia_semana", "hora_inicio"],
            },
        ),
        migrations.AddConstraint(
            model_name="declaraciondisponibilidad",
            constraint=models.UniqueConstraint(
                fields=("legajo", "periodo"), name="ddjj_unica_por_docente_y_periodo"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionhoraria",
            index=models.Index(
                fields=["version", "curso"], name="horarios_as_version_51488a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asignacionhoraria",
            index=models.Index(
                fields=["version", "legajo", "dia_semana"],
                name="horarios_as_version_50261c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="asignacionhoraria",
            constraint=models.UniqueConstraint(
                fields=("version", "curso", "bloque"),
                name="una_materia_por_bloque_y_curso",
            ),
        ),
        migrations.AddConstraint(
            model_name="asignacionhoraria",
            constraint=models.UniqueConstraint(
                condition=models.Q(("legajo__isnull", False)),
                fields=("version", "legajo", "dia_semana", "hora_inicio"),
                name="docente_en_un_solo_lugar_por_hora",
            ),
        ),
    ]
