# Generated by Django 5.1.15 on 2026-08-30 14:43

import core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("horarios", "0002_alter_declaraciondisponibilidad_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="declaraciondisponibilidad",
            name="archivo",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("ddjj"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="declaración firmada",
            ),
        ),
    ]
