# Generated by Django 5.1.15 on 2026-08-28 15:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("estructura", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Legajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        help_text="Opcional, el que usa la escuela.",
                        max_length=20,
                        verbose_name="número de legajo",
                    ),
                ),
                ("apellido", models.CharField(max_length=100, verbose_name="apellido")),
                ("nombre", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "cuil",
                    models.CharField(
                        max_length=13,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El CUIT/CUIL debe tener 11 dígitos (con o sin guiones).",
                                regex="^\\d{2}-?\\d{8}-?\\d$",
                            )
                        ],
                        verbose_name="CUIL",
                    ),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=15, verbose_name="DNI"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de nacimiento"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="teléfono"
                    ),
                ),
                (
                    "domicilio",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="domicilio"
                    ),
                ),
                (
                    "localidad",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="localidad"
                    ),
                ),
                (
                    "obra_social",
                    models.CharField(
                        blank=True,
                        help_text="Se informa al liquidador en el alta.",
                        max_length=100,
                        verbose_name="obra social",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        blank=True,
                        help_text="Primer día de trabajo en esta escuela.",
                        null=True,
                        verbose_name="ingreso a la institución",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ACTIVO", "Activo"), ("BAJA", "De baja")],
                        default="ACTIVO",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        blank=True,
                        help_text="Opcional: vincula el legajo con su acceso al sistema.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legajo",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuario del portal",
                    ),
                ),
            ],
            options={
                "verbose_name": "legajo",
                "verbose_name_plural": "legajos",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CARGO_BASE", "Cargo (jornada)"),
                            ("HORAS_CATEDRA", "Horas cátedra (40 min)"),
                            ("HORAS_RELOJ", "Horas reloj (60 min)"),
                        ],
                        max_length=15,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "denominacion",
                    models.CharField(
                        blank=True,
                        help_text='Para cargos que no son materia. Ej.: "Preceptor/a", "Secretaria".',
                        max_length=120,
                        verbose_name="denominación",
                    ),
                ),
                (
                    "horas_semanales",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="horas semanales",
                    ),
                ),
                (
                    "jornada_completa",
                    models.BooleanField(
                        default=False,
                        help_text="Solo para cargos de jornada.",
                        verbose_name="jornada completa",
                    ),
                ),
                (
                    "situacion_revista",
                    models.CharField(
                        choices=[
                            ("TITULAR", "Titular"),
                            ("PROVISIONAL", "Provisional / interino"),
                            ("SUPLENTE", "Suplente"),
                        ],
                        max_length=15,
                        verbose_name="situación de revista",
                    ),
                ),
                (
                    "fuente_pago",
                    models.CharField(
                        choices=[
                            ("SUBVENCIONADO", "Subvencionado (lo paga el estado)"),
                            ("INTERNO", "Interno (lo paga la escuela)"),
                        ],
                        help_text="Define si la novedad va a la planilla Oficial o a la Interna.",
                        max_length=15,
                        verbose_name="fuente de pago",
                    ),
                ),
                ("fecha_alta", models.DateField(verbose_name="alta")),
                (
                    "fecha_baja",
                    models.DateField(blank=True, null=True, verbose_name="baja"),
                ),
                (
                    "motivo_baja",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("RENUNCIA", "Renuncia"),
                            ("CESE", "Cese"),
                            ("FIN_SUPLENCIA", "Fin de suplencia"),
                            ("JUBILACION", "Jubilación"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=15,
                        verbose_name="motivo de baja",
                    ),
                ),
                (
                    "resolucion_numero",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="resolución n°"
                    ),
                ),
                (
                    "resolucion_fecha",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de la resolución"
                    ),
                ),
                (
                    "resolucion_archivo",
                    models.FileField(
                        blank=True,
                        upload_to="resoluciones/",
                        verbose_name="archivo de la resolución",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="observaciones"),
                ),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True,
                        help_text="Opcional: si las horas están asignadas a una división concreta.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="estructura.curso",
                        verbose_name="curso",
                    ),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="estructura.materia",
                        verbose_name="materia",
                    ),
                ),
                (
                    "nivel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cargos",
                        to="estructura.nivel",
                        verbose_name="nivel",
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="legajos.legajo",
                        verbose_name="legajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "cargo",
                "verbose_name_plural": "cargos",
                "ordering": ["legajo", "-fecha_alta"],
            },
        ),
        migrations.CreateModel(
            name="ServicioAnterior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institucion_nombre",
                    models.CharField(max_length=200, verbose_name="institución"),
                ),
                (
                    "cargo_descripcion",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="cargo desempeñado"
                    ),
                ),
                ("desde", models.DateField(verbose_name="desde")),
                ("hasta", models.DateField(verbose_name="hasta")),
                (
                    "es_docente",
                    models.BooleanField(
                        default=True,
                        help_text="Desmarcar si el servicio no computa como docente.",
                        verbose_name="antigüedad docente",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True, upload_to="servicios/", verbose_name="certificación"
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicios_anteriores",
                        to="legajos.legajo",
                        verbose_name="legajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "servicio anterior",
                "verbose_name_plural": "servicios anteriores",
                "ordering": ["legajo", "-desde"],
            },
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado en"),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej.: "Apto psicofísico".',
                        max_length=120,
                        verbose_name="nombre",
                    ),
                ),
                (
                    "lleva_vencimiento",
                    models.BooleanField(default=True, verbose_name="lleva vencimiento"),
                ),
                (
                    "dias_preaviso",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Con cuánta anticipación avisar que vence.",
                        verbose_name="días de preaviso",
                    ),
                ),
                (
                    "obligatorio",
                    models.BooleanField(default=False, verbose_name="obligatorio"),
                ),
                (
                    "institucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.institucion",
                        verbose_name="institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "tipo de documento",
                "verbose_name_plural": "tipos de documento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoLegajo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True, upload_to="documentos/", verbose_name="archivo"
                    ),
                ),
                (
                    "fecha_emision",
                    models.DateField(blank=True, null=True, verbose_name="emitido el"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(blank=True, null=True, verbose_name="vence el"),
                ),
                (
                    "observaciones",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="observaciones"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="cargado en"),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="legajos.legajo",
                        verbose_name="legajo",
                    ),
                ),
                (
                    "tipo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documentos",
                        to="legajos.tipodocumento",
                        verbose_name="tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "documento del legajo",
                "verbose_name_plural": "documentación",
                "ordering": ["legajo", "tipo"],
            },
        ),
        migrations.CreateModel(
            name="Titulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("TITULO", "Título"),
                            ("POSTITULO", "Postítulo"),
                            ("CURSO", "Curso / capacitación"),
                        ],
                        default="TITULO",
                        max_length=12,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=200, verbose_name="denominación"),
                ),
                (
                    "institucion_otorgante",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="otorgado por"
                    ),
                ),
                (
                    "fecha_egreso",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de egreso"
                    ),
                ),
                (
                    "horas_reloj",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Para cursos y capacitaciones.",
                        null=True,
                        verbose_name="horas reloj",
                    ),
                ),
                (
                    "registrado",
                    models.BooleanField(
                        default=False,
                        help_text="Título registrado ante el organismo.",
                        verbose_name="registrado",
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        blank=True, upload_to="titulos/", verbose_name="archivo"
                    ),
                ),
                (
                    "legajo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titulos",
                        to="legajos.legajo",
                        verbose_name="legajo",
                    ),
                ),
            ],
            options={
                "verbose_name": "título",
                "verbose_name_plural": "títulos y formación",
                "ordering": ["legajo", "-fecha_egreso"],
            },
        ),
        migrations.AddIndex(
            model_name="legajo",
            index=models.Index(
                fields=["institucion", "apellido", "nombre"],
                name="legajos_leg_institu_a5b4f0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="legajo",
            constraint=models.UniqueConstraint(
                fields=("institucion", "cuil"), name="legajo_unico_por_cuil"
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["institucion", "fuente_pago"],
                name="legajos_car_institu_164c95_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cargo",
            index=models.Index(
                fields=["legajo", "fecha_alta"], name="legajos_car_legajo__8e548f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tipodocumento",
            constraint=models.UniqueConstraint(
                fields=("institucion", "nombre"), name="tipo_documento_unico_por_nombre"
            ),
        ),
        migrations.AddIndex(
            model_name="documentolegajo",
            index=models.Index(
                fields=["fecha_vencimiento"], name="legajos_doc_fecha_v_8c6a5a_idx"
            ),
        ),
    ]
