# Generated by Django 5.1.15 on 2026-08-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estructura", "0001_initial"),
        ("legajos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legajo",
            name="materias_que_puede_dar",
            field=models.ManyToManyField(
                blank=True,
                help_text="Para buscarle reemplazo a un curso sin docente.",
                related_name="personal_habilitado",
                to="estructura.materia",
                verbose_name="materias que puede dar",
            ),
        ),
    ]
