# Generated by Django 5.1.15 on 2026-08-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0002_materias_que_puede_dar"),
    ]

    operations = [
        migrations.AddField(
            model_name="legajo",
            name="plantel",
            field=models.CharField(
                choices=[
                    ("DOCENTE", "Docente"),
                    ("PRECEPTOR", "Preceptor/a"),
                    ("DIRECTIVO", "Directivo"),
                    ("ADMINISTRATIVO", "Administrativo"),
                    ("MAESTRANZA", "Maestranza / ordenanza"),
                ],
                default="DOCENTE",
                help_text="Docente, preceptor, directivo, administrativo o maestranza. Separa las secciones de Personal y define a quién se le buscan materias para cubrir cursos.",
                max_length=15,
                verbose_name="plantel",
            ),
        ),
    ]
