# Generated by Django 5.1.15 on 2026-08-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0003_plantel"),
    ]

    operations = [
        migrations.AddField(
            model_name="legajo",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Tipo carnet, cuadrada (4x4). JPG o PNG; si no es exactamente cuadrada, se recorta al mostrarla.",
                upload_to="fotos/",
                verbose_name="foto",
            ),
        ),
    ]
