# Generated by Django 5.1.15 on 2026-08-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0004_foto"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentolegajo",
            name="reclamado_en",
            field=models.DateTimeField(
                blank=True,
                help_text="Cuándo se le avisó por última vez a la persona que vence.",
                null=True,
                verbose_name="último reclamo",
            ),
        ),
    ]
