# Generated by Django 5.1.15 on 2026-08-30 14:43

import core.archivos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legajos", "0006_alter_cargo_resolucion_archivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cargo",
            name="resolucion_archivo",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("resoluciones"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="archivo de la resolución",
            ),
        ),
        migrations.AlterField(
            model_name="documentolegajo",
            name="archivo",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("documentos"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="archivo",
            ),
        ),
        migrations.AlterField(
            model_name="legajo",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Tipo carnet, cuadrada (4x4). JPG o PNG; si no es exactamente cuadrada, se recorta al mostrarla.",
                upload_to=core.archivos.CarpetaProtegida("fotos"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="foto",
            ),
        ),
        migrations.AlterField(
            model_name="servicioanterior",
            name="archivo",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("servicios"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="certificación",
            ),
        ),
        migrations.AlterField(
            model_name="titulo",
            name="archivo",
            field=models.FileField(
                blank=True,
                upload_to=core.archivos.CarpetaProtegida("titulos"),
                validators=[core.archivos.validar_adjunto],
                verbose_name="archivo",
            ),
        ),
    ]
