# Generated by Django 5.1.15 on 2026-08-30 23:11

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_intentos_de_acceso"),
        ("estructura", "0001_initial"),
        ("legajos", "0007_alter_cargo_resolucion_archivo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="legajo",
            name="legajo_unico_por_cuil",
        ),
        migrations.AlterField(
            model_name="legajo",
            name="cuil",
            field=models.CharField(
                blank=True,
                help_text="Es la identidad de la persona para la liquidación. Puede quedar vacío al arrancar y completarse después; mientras tanto figura como pendiente.",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El CUIT/CUIL debe tener 11 dígitos (con o sin guiones).",
                        regex="^\\d{2}-?\\d{8}-?\\d$",
                    )
                ],
                verbose_name="CUIL",
            ),
        ),
        migrations.AddConstraint(
            model_name="legajo",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cuil", ""), _negated=True),
                fields=("institucion", "cuil"),
                name="legajo_unico_por_cuil",
            ),
        ),
    ]
